### ISSUE TITLE
cdn import broke at 1.0.0

### ISSUE THREAD

**Issue by dskvr** [SamSamskies/nostr-zap#26]
Starting at `v1.0.0` cnd script (unpkg) starts throwing:

```
Uncaught TypeError: Cannot read properties of null (reading 'appendChild')
    at $ba417727cf57ac1f$export$1ab5838465dbd10a (view.js:668:17)
    at index.js:3:1
```

last working version is `0.22.0`

```
<script src="https://cdn.jsdelivr.net/npm/nostr-zap@0.22.0"></script>
```

**Comment by SamSamskies** [comment]
Can you provide any more details? A Code Sandbox that reproduces the issue would be awesome. I've been using it on my apps and have not experienced this. For example, https://notazap.vercel.app is running v.1.1.0 from the CDN.

https://github.com/SamSamskies/notazap.lol/blob/172ec5a95a04b7a6460c8e8ff74c75f1e91591b6/public/initScript.js#L73

**Comment by SamSamskies** [comment]
What browser are you using?

**Comment by SnowCait** [comment]
I got the same error with plain HTML and Svelte (SvelteKit).
I checked it in Chrome and Edge.

In plain HTML, it works when I move `<script />` to the end of the `<body />` (like on your site), but that's not possible with Svelte, so I'd be happy if it worked in the `<head />`.

Adding `defer` or `async` to `<script />` also worked, but I'm not sure if it's reliable (whether the timing is guaranteed).
Edit: [`defer`](https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/script#defer) seems to be guaranteed to be executed after the document has been parsed.

e.g. index.html

```html
<!doctype html>
<html>
	<head>
		<script src="https://cdn.jsdelivr.net/npm/nostr-zap@latest"></script>
	</head>
	<body>
		<button
			data-npub="npub1vp8fdcyejd4pqjyrjk9sgz68vuhq7pyvnzk8j0ehlljvwgp8n6eqsrnpsw"
			data-relays="wss://relay.damus.io,wss://relay.snort.social,wss://nostr.wine,wss://relay.nostr.band"
		>
			Zap Me ⚡️
		</button>
	</body>
</html>
```

e.g. +page.svelte
```svelte
<svelte:head>
    <script src="https://cdn.jsdelivr.net/npm/nostr-zap@latest"></script>
</svelte:head>

<button
    data-npub="npub1vp8fdcyejd4pqjyrjk9sgz68vuhq7pyvnzk8j0ehlljvwgp8n6eqsrnpsw"
    data-relays="wss://relay.damus.io,wss://relay.snort.social,wss://nostr.wine,wss://relay.nostr.band"
>
  Zap Me ⚡️
</button>
```
